- name: Install apt packages
  apt:
    name: ['i3', 'i3blocks', 'fonts-font-awesome', 'lxappearance', 'xclip', 'maim', 'vifm', 'feh', 'dconf-cli', 'python3-pip']
    update_cache: yes
  become: True

- name: Install snap packages
  shell: "snap install --classic {{ item }}"
  become: True
  with_items:
    - notable
    - code

- name: Install pip packages
  pip:
    requirements: "{{ playbook_dir }}/files/requirements.txt"
