set number
set relativenumber

set tabstop=4
set shiftwidth=4
set smarttab

set showmatch
set hlsearch
set incsearch
set ignorecase

set listchars=tab:··
set list


" Setup Vundle plugin manager
set nocompatible              " be iMproved, required
filetype off                  " required


set rtp+=~/.vim/bundle/Vundle.vim " set the runtime path to include Vundle and initialize

call vundle#begin()
Plugin 'VundleVim/Vundle.vim' " let Vundle manage Vundle, required
Plugin 'lifepillar/vim-solarized8'
call vundle#end()            " required

filetype plugin indent on    " required
