- name: Install i3wm on Ubuntu
  import_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Install i3wm on CentOS
  import_tasks: centos.yml
  when: ansible_distribution == 'CentOS'

- name: Place configs 
  import_tasks: configs.yml
